Proyecto-ISPP/FISIOFIND

docs/planification/communication_plan.md

Co-authored-by: Francisco Mateos Villarejo <framatvil@alum.us.es>

docs: communication management plan document 

---

docs/02_planification/general_sprint_planning.md

Hechos algunos cambios para seguir completando el general sprint planning. Se hace pr para que pueda estar en main para la reunión de esta tarde aunque no esté terminado.

docs: progreso en puntos de tarea y planes en general_sprint_planning.md

---

docs/02_planification/requirements_registry.md

Se han añadido y editado algunos requisitos funcionales y añadido no funcionales

doc: Registro de requisitos actualizado

---

.github/workflows/codeql.yml

creado workflow codeql.yml. Github te lo crea automaticamente y te deja configurarlo.
Es un requisito que la aplicación sea segura. A partir de ahora, siempre que se haga un push o pull request a develop o a main, saltará este workflow que hará un escaneo del código en búsqueda de vulnerabilidades. Eso sí, no ejecutará la aplicación, sino que solo hará un escaneo del código para buscar patrones sospechosos. Estas vulnerabilidades podrán ser analizadas a través de la sección de seguridad(*Security*) de Github, pudiendo solucionarlas o descartarlas.
- No aplica.

feat: creado workflow codeql.yml con github

---

docs/03_reports/quality_reports/quality_report_06-03-2025.md

Realizar la plantilla correspondiente a la primera mitad del Sprint 1.

docs: Plantilla del documento de Análisis cuantitativo de la calidad

---

docs/03_reports/ia_reports/ia_report_week_4-5.md

Realizar X funcionalidad añadiendo X datos referente al requisito RNN-0NM...
- Cambio 1
- Cambio 2
- ...
- Se ha mejorado ...
- Se ha completado ...
- ...
- Se deben hacer tests unitarios
- Se debe comprobar que el cambio funciona correctamente
- ...

docs: Añadido reporte de ia semanas 4 y 5

---

docs/05_knowledge_base/feedback_07-03-2025.md

Realización del documento de feedback de la clase con fecha 07/03/2025
- Mantener un registro de los comentarios de los profesores y compañeros para mejorar progresivamente.
- Revisión del documento

docs: Feedback del 07/03/2025

---

docs/03_reports/ia_reports/ia_report_Sprint-1.md

Añadido el reporte de ia del Sprint 1.
Monitorear y mejorar el uso de la ia el proyecto.
Closes #138

docs: Reporte de ia Sprint 1

---

docs/04_monitoring/sprint_1/sprint_retrospective.md

Co-authored-by: Pablo Fernández <Letee2@users.noreply.github.com>
Closes Sprint Retrospective #S1 Grupo 1 #192

docs: Retrospectiva Sprint 1-G1

---

docs/02_planification/user_stories_registry.md
docs/04_monitoring/sprint_1/sprint_planning_#1.md
docs/04_monitoring/sprint_2/mid_term_retrospective_#S2.md
docs/04_monitoring/sprint_2/sprint_planning_#2.md

- Se ha elaborado el documento de Sprint Planning de este sprint
- Se han creado y asignado todas las tareas y HU en el *GitHub Project*
- Realizar la documentación de planificación necesaria del #S2
- Comprobar que no se producen conflictos, si es así mergear directamente

docs: elaboración de sprint planning #S2

---

docs/04_monitoring/meetings/meeting_19-03-2025.md

Se ha realizado el documento que recoge la matriz RACI del grupo 2

doc: matriz raci grupo 2

---

docs/03_reports/ia_reports/ia_report_week_7.md

Reporte uso de la ia semana 7 (Primera iteración del Sprint 2) #141

docs: Reporte de ia semana 7 (Primera iteración Sprint 2)

---

frontend/app/globals.css
frontend/app/page.tsx

fix: imágenes dinámicas de la home con responsividad

---

docs/05_knowledge_base/feedback_14-03-2025.md

Realización del documento de feedback de la sesión con fecha 14/03/2925
- Guardar en la base de conocimiento interna del grupo el feedback generado durante la sesión para así tener un registro de aspectos positivos y puntos a mejorar
- Revisar el documento

docs: Feedback 14-03-2025

---

backend/fisio_find/sesion_invitado/urls.py
frontend/app/page.tsx
frontend/components/ui/Wizard.tsx

Corregir detalles para el despliegue.
- Se ha corregido la ruta de especializaciones en el backend
- Se han corregido algunas llamadas al servidor para que funcione en el despliegue

fix: solucionados errores de rutas para entornos y de vistas

---

frontend/app/videocalls/Room.jsx
frontend/app/videocalls/hooks/useRoomManagement.js
frontend/app/videocalls/page.tsx

He añadido los cambios  referentes al requisito RFC-#324
- Cambio 1: En la pagina de videollamadas, ahora en vez de elegir tu rol, se detecta automaticamente por backend. Si no estas loggeado, te muestra un mensaje de advertencia y redireccion a login.
- Cambio 2: Dentro de la videollamada, ya no  comprobamos el rol por la URL , si no que de nuevo comprobamos desde backend.
- Cambio 3: Si no estas loggeado e intentas acceder a una videollamada, se muestra la misma advertencia que en la pagina de creacion/unión a videollamada.
- Cambio 4: Al colgar como paciente, redirigimos a home page para evitar error de página no encontrada.
- El motivo de estos cambios es restringir el uso de esta herramienta a los roles correspondientes. Queda …

Rfc/integrar usuarios videollamadas 

---

docs/05_knowledge_base/feedback_21-03-2025.md

Documento de feedback de la clase del 23/03/2025
- Guardar el feedback de los profesores para tener en nuestra base de conocimientos los aspectos a mejorar y positivos de nuestras presentaciones y nuestro proyecto.
- Revisar el documento.

docs: Documento de feedback 21/03

---

frontend/app/videocalls/Room.jsx

Ahora en Room.jsx:
- Se valida rol a través de llamada a API
- Se ocultan de nuevo herramientas a paciente
- Se han recuperado cambios de Mapa de Dolor que se habían pisado al integrar cambios

fix: Herramientas en videollamada para paciente

---

docs/03_reports/ia_reports/ia_report_Sprint-2.md

Adición del reporte de IA del Sprint 2

docs: Reporte de ia del Sprint 2

---

frontend/app/videocalls/Room.module.css
frontend/app/videocalls/ToolsContainer.jsx
frontend/app/videocalls/tools/Templates.jsx

Se han borrado los mockups de la vista de videollamdas
Se quiere borrar aquello que no se va a continuar
- Comprobar que lo borrado son solo mockups

feat:borrados mockups de vista videollamadas

---

frontend/app/physio-management/profile/page.tsx

Realizar X funcionalidad añadiendo X datos referente al requisito RNN-0NM...
- Cambio 1
- Cambio 2
- ...
- Se ha mejorado ...
- Se ha completado ...
- ...
- Se deben hacer tests unitarios
- Se debe comprobar que el cambio funciona correctamente
- ...

fix: correcciones en pantalla fisio, select, estilos, y vista del plan

---

docs/04_monitoring/meetings/meeting_15-03-2025.md

- Acta de reunión del G3 fecha  15-03-2025
- Realización de la matriz RACI
- Intencionalmente en blanco

Docs: Acta reunión G3  15-03-2025

---

docs/04_monitoring/sprint_3/sprint_planning_#3.md

Se ha realizado el documento Sprint Planning 3 acorde a lo hablado en la reunion del 29/03 y al Sprint Planning General
- Genera una documentación Sprint adecuada para este último Sprint
- He pasado el filtro de faltas de ortografía, así que simplemente te lo puedes leer y cambiar o añadir algo si lo ves oportuno

docs: sprint planning 3 terminado

---

backend/fisio_find/fisio_find/settings.py

Realizar X funcionalidad añadiendo X datos referente al requisito RNN-0NM...
- Cambio 1
- Cambio 2
- ...
- Se ha mejorado ...
- Se ha completado ...
- ...
- Se deben hacer tests unitarios
- Se debe comprobar que el cambio funciona correctamente
- ...

fix: arreglar settings.py

---

backend/fisio_find/fisio_find/settings.py
frontend/app/videocalls/hooks/useWebRTC.js

Se configura el servidor TURN para las videollamadas
**Motivacion del cambio**
Conseguir usar las videollamadas en redes más privadas

feat: Cambios para el servidor turn en videollamadas

---

backend/fisio_find/appointment/views.py
backend/fisio_find/payment/urls.py
backend/fisio_find/payment/views.py
frontend/components/CheckoutForm.tsx
frontend/components/ui/WizardContent.tsx
frontend/components/ui/appointment-modal.tsx

Corregir y mejorar el proceso de pago y cancelación de citas.
- Arreglos y mejoras visuales en el proceso de reserva de citas.
- Corrección del flujo de cancelaciones (como fisioterapeuta) de citas de las próximas 48 horas.
- Se ha mejorado la interfaz y funcionamiento del proceso de reserva de pagos
- Se ha corregido y revisado el flujo completo de cancelación de citas, teniendo en cuenta todas las casuísticas posibles.

Correción de procesos de pago y cancelación de citas.

---

backend/fisio_find/users/urls.py
backend/fisio_find/users/views.py
frontend/app/physio-management/profile/page.tsx
frontend/components/ui/Alert.tsx
frontend/components/ui/ConfirmModal.tsx
frontend/components/ui/WizardContent.tsx

Arreglar distintos bugs sobre cuestionarios de los servicios
- Correcto funcionamiento de crear, updatear y borrar servicios
- Arreglo en los layouts de las celdas de los cuestionarios

fix: Bugs sobre cuestionarios y servicios arreglados

---

docs/03_reports/ia_reports/ia_report_week_9.md

Realizar el reporte de IA de la semana 9 (Primera semana del Sprint 3)

feat: Reporte de ia para presentación del 04/04

---

frontend/app/page.tsx

Se ha creado un nuevo footer mas moderno y acorde al diseño de la nueva home
- Comprobar que todos los links del footer funcionan bien (las rrss deben abrirse en una nueva pestaña)

style: nuevo footer

---

backend/fisio_find/users/validacionFisios.py

feat: logging en script validacion

---

.github/workflows/process_payments.yml

Corrección en el workflow de GitHub Actions para procesar pagos, asegurando el uso adecuado de la variable BASE_URL configurada en GitHub.
- Se define BASE_URL correctamente mediante ${{ vars.BASE_URL }} en el comando curl.
- Se garantiza que PAYMENT_API_KEY se mantenga como un secreto seguro.
- Se ha corregido un error en la interpolación de la variable BASE_URL, evitando posibles fallos en la ejecución del workflow.
- Se garantiza que la API de procesamiento de pagos reciba correctamente la URL base definida en la configuración de GitHub.
**Instrucciones:**
Se deben verificar los logs de ejecución del workflow en GitHub Actions.
Se debe comprobar que la llamada a la API se realiza correctamente sin errores de autenticación ni de URL …

fix: corrección del workflow de procesamiento de pagos

---

backend/fisio_find/appointment_rating/tests.py
backend/fisio_find/appointment_rating/urls.py
backend/fisio_find/appointment_rating/views.py

**Descripción del cambio:**  
Realizar pruebas automatizadas integrando una suite de tests para el componente `AppointmentRating`, referente al requisito **HF-005: Valoración del fisioterapeuta**.  
- Añadida clase `AppointmentRatingIntegrationTests` con pruebas de integración para endpoints y lógica de valoración.  
- Añadida clase `AppointmentRatingCoverageTests` con pruebas de cobertura para casos límite y excepciones.  
- Incluye validación del método `__str__()` del modelo `AppointmentRating`.  
- Se prueba la gestión de errores como `ObjectDoesNotExist` y `NoReverseMatch`.  
---
**Motivación e impacto:**  
- Se ha mejorado la **cobertura del código** asegurando la correcta funcionalidad del sistema de valoraciones.  
- Se ha completado una parte importante del plan de pruebas de la …

test: suite de tests de appointment_ratings (alto coverage)

---

README.md

Se ha actualizado el readme con la estructura nueva generada y el roadmap.
Closes #490

feat: readme actualizado S3

---

docs/SPRINT 3/revision.md

Documento revisión
- Cumplir con condiciones de fallo
- Comprobara links
- Comprobar que esta todo lo que se debe revisar y se entiende

docs: creado documento revision

---

docs/05_knowledge_base/feedback/feedback_11-04-2025.md

Feedback de la clase del 11/04/2025
- Revisar el documento

docs: Primera versión feedback 11-04

---

backend/selenium_tests/fisio find.side
backend/selenium_tests/instrucciones.txt

Se han creado algunos tests de selenium. El resto de tests de harán cuando se vayan mergeando el resto de funcionalidades.
- Probar el correcto funcionamiento de la app
- Probar los tests de selenium con el add-on https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/
- Lo que se sube es un solo proyecto con muchos tests, se debe de importar con el add on
- Algunos tests necesitan de pasos intermedios. Por ejemplo, el paso de tratamientos necesita que se ponga una cita como finalizada.

test: tests de selenium

---

backend/fisio_find/fisio_find/urls.py
frontend/public/robots.txt

Creados archivos robots.txt para frontend y backend
Evitar que se indexen rutas indeseadas
- Comprobar que funciona (se puede entrar a /robots.txt desde el backend y el frontend)
- Comprobar que las urls en disallow no están mal escritas
- Comprobar que las urls que he bloqueado/permitido tienen sentido

feat: creados archivos robots.txt para backend y frontend

---

backend/fisio_find/appointment_rating/admin.py
backend/fisio_find/guest_session/views.py
frontend/app/advanced-search/page.tsx

Arreglado busqueda avanzada valoraciones que estaba mocked
Que funcione la búsqueda avanzada y valoraciones correctamente
- Valorar un fisio (se puede hacer desde el panel de admin appointment_rating)
- Probar que se ve reflejado en búsqueda avanzada

fix: arreglado busqueda avanzada valoraciones estaba mocked

---

backend/fisio_find/users/serializers.py
backend/fisio_find/users/util.py
frontend/app/register/patient/page.tsx

Resolución de los bugs del formulario de registro de pacientes
- Se han arreglado los problemas en el formulario
- Se debe comprobar que la solución aportada es la que se buscaba

fix: solución bugs 1, 2, 3, 4 (Modulo: Registro paciente)

---

docs/WPL/revision.md

Creado revision.md
- Cumplir con las condiciones de fallo
- Revisar el documento

docs: creado revision.md
